services:
  app:
    build: .
    container_name: accounting-backend
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_API=${TELEGRAM_BOT_API}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - EINVOICE_PHONE=${EINVOICE_PHONE}
      - EINVOICE_PASSWORD=${EINVOICE_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TZ=Asia/Taipei
    volumes:
      - ./:/app

    network_mode: "host"
    

# how to use:
# docker-compose up -d --build